name: Check library
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Slate
        uses: actions/checkout@v2
        with:
          repository: sreichelt/slate
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install NPM dependencies
        run: npm ci
      - name: Checkout library
        uses: actions/checkout@v2
        with:
          path: data/libraries/hlm
      - name: Check library
        run: src/scripts/checkLibrary.sh
