name: Check library
on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Slate
        uses: actions/checkout@v2
        with:
          repository: sreichelt/slate
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules
      - name: Install NPM dependencies
        run: npm install
      - name: Checkout library
        uses: actions/checkout@v2
        with:
          path: data/libraries/hlm
      - name: Check library
        run: src/scripts/checkLibrary.sh
